//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffineTransformations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AffineTransformations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница: {0}.
        /// </summary>
        public static string AuthorHomepageTitle {
            get {
                return ResourceManager.GetString("AuthorHomepageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://SixEightOne.eu/.
        /// </summary>
        public static string AuthorHomepageValue {
            get {
                return ResourceManager.GetString("AuthorHomepageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инж. Н. Гешков.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор: {0}.
        /// </summary>
        public static string AuthorNameTitle {
            get {
                return ResourceManager.GetString("AuthorNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инж. Н. Гешков.
        /// </summary>
        public static string AuthorNameValue {
            get {
                return ResourceManager.GetString("AuthorNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлът {0} не може да бъде намерен!.
        /// </summary>
        public static string ExceptionFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден формат на данните на ред: {0}!.
        /// </summary>
        public static string ExceptionInvalidRowData {
            get {
                return ResourceManager.GetString("ExceptionInvalidRowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка:.
        /// </summary>
        public static string MessageBoxTitleError {
            get {
                return ResourceManager.GetString("MessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация:.
        /// </summary>
        public static string MessageBoxTitleInformation {
            get {
                return ResourceManager.GetString("MessageBoxTitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание:.
        /// </summary>
        public static string MessageBoxTitleWarning {
            get {
                return ResourceManager.GetString("MessageBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстови файлове|*.txt.
        /// </summary>
        public static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочетени точки: {0}{3}Общи точки в двете координатни системи: {1}{3}Точки за трансформиране: {2}.
        /// </summary>
        public static string OpenFileDialogMessageSuccess {
            get {
                return ResourceManager.GetString("OpenFileDialogMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание: {0}.
        /// </summary>
        public static string ProductDescriptionTitle {
            get {
                return ResourceManager.GetString("ProductDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Програма за трансформация на XY координати чрез афинна трансформация.
        /// </summary>
        public static string ProductDescriptionValue {
            get {
                return ResourceManager.GetString("ProductDescriptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на програма: {0}.
        /// </summary>
        public static string ProductNameTitle {
            get {
                return ResourceManager.GetString("ProductNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Афинна трансформация.
        /// </summary>
        public static string ProductNameValue {
            get {
                return ResourceManager.GetString("ProductNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия: {0}.
        /// </summary>
        public static string ProductVersionTitle {
            get {
                return ResourceManager.GetString("ProductVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За програмата.
        /// </summary>
        public static string uxMenuCategoryAboutHeader {
            get {
                return ResourceManager.GetString("uxMenuCategoryAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактиране .
        /// </summary>
        public static string UxMenuCategoryEdit {
            get {
                return ResourceManager.GetString("UxMenuCategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string UxMenuCategoryFile {
            get {
                return ResourceManager.GetString("UxMenuCategoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощ.
        /// </summary>
        public static string UxMenuCategoryHelp {
            get {
                return ResourceManager.GetString("UxMenuCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За програмата.
        /// </summary>
        public static string UxMenuItemAboutHeader {
            get {
                return ResourceManager.GetString("UxMenuItemAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за програмата.
        /// </summary>
        public static string UxMenuItemAboutToolTip {
            get {
                return ResourceManager.GetString("UxMenuItemAboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За програмата.
        /// </summary>
        public static string UxMenuItemButtonAboutHeader {
            get {
                return ResourceManager.GetString("UxMenuItemButtonAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показване на резултата от трансформацията на екрана.
        /// </summary>
        public static string UxMenuItemLogHeader {
            get {
                return ResourceManager.GetString("UxMenuItemLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отваряне на файл.
        /// </summary>
        public static string UxMenuItemOpenFileHeader {
            get {
                return ResourceManager.GetString("UxMenuItemOpenFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отваряне на файл с координати на точки.
        /// </summary>
        public static string UxMenuItemOpenFileToolTip {
            get {
                return ResourceManager.GetString("UxMenuItemOpenFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис на файл.
        /// </summary>
        public static string UxMenuItemSaveFileHeader {
            get {
                return ResourceManager.GetString("UxMenuItemSaveFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записване на файл с координати на твърдия диск или друго устройство.
        /// </summary>
        public static string UxMenuItemSaveFileToolTip {
            get {
                return ResourceManager.GetString("UxMenuItemSaveFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансформиране на координати.
        /// </summary>
        public static string UxMenuItemTransformCoordinatesHeader {
            get {
                return ResourceManager.GetString("UxMenuItemTransformCoordinatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансформиране на координати.
        /// </summary>
        public static string UxMenuItemTransformCoordinatesToolTip {
            get {
                return ResourceManager.GetString("UxMenuItemTransformCoordinatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Афинна трансформация.
        /// </summary>
        public static string UxWindowTitle {
            get {
                return ResourceManager.GetString("UxWindowTitle", resourceCulture);
            }
        }
    }
}
